### PR TITLE
Update to CKEditor and adding Image Manager

### PR DESCRIPTION
**Pull request by krazykelv**
Just a few comments...

I've changed CKEditor so it edits inline now because the latest version 4.0 supports that.  I think it looks much nicer like that although there could be some catches I'm not aware of.

For the file manager I needed a newer jQuery version, so I've added a conditional into the header so it uses a newer version just for the file manager.  Once we update the global jQuery file this can be removed.

I'm using an image cache folder for the file manager thumbnails, however these files never get deleted unless you do it manually.  Wasn't sure what the best way to handle that was without checking each file on the page load.

### CODE REVIEW

**Comment by krazykelv** [comment]
I'll start working on those other things.  A lot of this code I copied from the Opencart project, so that's why there may be a few funny bits of code that don't look like they belong.  I did clean it up but obviously missed a lot.

**Comment by soonick** [comment]
Thanks for your help with this feature. I am sure everyone will love it.

I am not very familiar with CKE so if you feel my questions are out of context of there is a reason to do things that way, feel free to tell me and we can work on getting it it.

Thanks,
Adrian

**Comment by krazykelv** [comment]
Hi Adrian.  Just wondering if you saw my latest commit here...

**Comment by soonick** [comment]
Thanks for reminding me. Somehow I had missed your update.

It looks a lot better now. I will take a more detailed look during the week and let you know my updates.

**Comment by soonick** [comment]
Hello,

I finally got a chance to play with the new feature and I have a few questions.

beforeClick

When I arrived to this page I was confused because I didn't see the text editor on the top of the tab. I think it would be better to have the yellow rectangle look like a normal text area. Probably having the text editor button always visible would make it more apparent that it is a wysiwyg editor.
Is the --> after the rectangle intentional?

clicked

Somehow having the controls pop up like that doesn't seem right. Can we have them always visible?
Also it would be awesome if we could have a theme that looks more like the previous. If there isn't one or is to difficult you don't have to worry about it.

Thanks for your help,
Adrian

**Comment by krazykelv** [comment]
Ok I've pushed some new changes...

I'm not sure if there's a way to always display the editor buttons, but I've just made it so the focus starts in the editor box, which means the buttons will display when you first go to the Compose page.

I've improved the styling of the editor box

For the theme... You can still use the old theme, but this one is the new default theme for CKEditor so I thought it might be better to stick to the default one as it probably means less complications overall for the future.

**Comment by soonick** [comment]
Thanks for the updates.

I added a new branch to my repository (update-editor) with your changes. I also added a commit on top of your changes to make the editor toolbox always visible. I haven't tested the file upload functionality yet, but it feels like there is still some polishing to do.

I am guessing it will take a while to integrate this feature into master, but once we do it is going to be awesome. If you want to help with the polishing I will be happy to review your changes.

Thanks a lot for your help.

**Comment by krazykelv** [comment]
Ok sounds good.  If you can think of some specific polishing jobs then maybe I could help out with those.  Otherwise I'll leave it in your capable hands as I imagine it might be hard to delegate lots of micro polishing jobs.

**Comment by soonick** [comment]
Hello @krazykelv,

Sorry for taking so long to take a look at this. Today I tried to upload an image using this feature but I am getting an error:

error

I also took a look at filemanager.php and I didn't see any code to handle the action=upload. Can you please take a look?

**Comment by krazykelv** [comment]
Hi Adrian

I think that error would mostly happen if the server didn't have write
permissions in the upload folder.  Try setting write permissions in the
folders uploadedimages/cache and uploadedimages/data.  If that's the case
it's probably a good idea to change that error message.  Is there
permissions checking somewhere for the attachments folder?

Kelvin

**Comment by soonick** [comment]
Hello Kelvin,

Thanks for the quick reply. I don't remember if we check for permissions for the attachments folder. We might have the same issue. I'll add something to show a better error message.

Thanks,
Adrian

**Comment by soonick** [comment]
Hey Kelvin,

I have merged your change and it is now available to everybody. Thanks a lot for your hard work.

**Comment by krazykelv** [comment]
Hi Adrian

No problem, and nice to see it finally released :)

Kelvin

**Pull request merged**
