### PR TITLE
add support for MySQL compressed and encrypted connections

### PR DESCRIPTION
**Pull request by ghost**
http://us2.php.net/manual/en/mysql.constants.php#mysql.client-flags

Added the ability to toggle off the use of compressed or SSL connections to the MySQL database. If a database requires a secure connection poMMo does not have the ability to connect. This adds the ability to enable it. Also adds compression to the connection as as an option as well.

P.S. : not sure why the diff for the config files looks like that, but only two config options were added. I assume since the whitespace changed or the lines changed Github is showing it that way.

### CODE REVIEW

**Comment by soonick** [comment]
Hello @KyraD,

Thanks for submitting this pull request, it looks very good. Can you please fix the first commit so it only shows the lines you added? As you said this is probably because your editor changed the white space on the file, but having it the way it is right now will make it hard to understand what actually changed.

Thanks,
Adrian

**Comment by ghost** [comment]
@soonick I had used the Github online editor for all the files, and even checked via the 'Preview' tab to make sure the diffs were correct and all were. I'm thinking the online editor was doing something funky which the preview was not showing me. I'm not sure how to revert that file to the original without destroying the fork and redoing it all. Sorry, I'm rather a noob when it comes to Git =o)

**Comment by soonick** [comment]
Hello @KyraD,

This is how I would do it:
- Revert the commit: **git revert cdb59c2**
- Modify the config file with your favorite editor adding only what you need
- Commit your new change. Now you will have 5 commits that correspond to your change.
- Rebase everything into one commit: **git rebase -i HEAD~5**
- Now you will have an editor open with 5 lines at the top that look something like this:

``` bash
pick cdb59c2 add config options for MySQL compressed and encrypted connections
pick c7ee46d add support for MySQL compressed and encrypted connections
pick bcc12a9 Pass compress and secure configs to database instance
pick 14499ba Revert "add config options for MySQL compressed and encrypted connections"
pick 6d0695c Adding things to config file
```
- Change it so it looks like this:

``` bash
pick cdb59c2 add config options for MySQL compressed and encrypted connections  
s c7ee46d add support for MySQL compressed and encrypted connections  
s bcc12a9 Pass compress and secure configs to database instance  
s 14499ba Revert "add config options for MySQL compressed and encrypted connections"  
s 6d0695c Adding things to config file  
```
- Save the file and quit the editor
- A new editor window will open showing you the commit messages for all the commits. Delete all those messages and add a new one describing the feature as a whole. Save and quit.

Now you should have only one commit with all your changes.
Let me know if anything is not clear.

Regards,
Adrian

**Comment by soonick** [comment]
Hello @KyraD,

Were you able to make those changes? Let me know if you need any help.

**Comment by ghost** [comment]
@soonick  Sorry, I've just been busy with other things. I'll get around to this when I have the time. =o)

**Comment by ghost** [comment]
@soonick omg, it looks like I messed it up even more =o(

**Comment by soonick** [comment]
Hello @KyraD,

It seems like you reverted the commit and then you created a new commit with just the correct changes in the config file. This is good so far. The only thing you need to do now is the rebase step, did you try it?

**Comment by ghost** [comment]
@soonick this is what I get when I do the rebase and save and close editor:

> fatal: Not a valid object name 14499ba
> fatal: Needed a single revision
> Invalid commit name: 14499ba

**Comment by soonick** [comment]
Hey @KyraD,

I looked at your commit history and I don't see any commit with that hash. Can you add a screenshot of how your editor screen looks like when you are doing the rebase (before you close the window).

Thanks,
Adrian

**Comment by ghost** [comment]
@soonick if you see https://github.com/soonick/poMMo/pull/172/files it correctly shows the changes now. Is it good to merge now?

**Comment by soonick** [comment]
Hello @KyraD,

It does show the correct changes, but it should be one commit instead of 5. Can you squash them into a single commit and submit a new pull request?

**Comment by ghost** [comment]
Now?

**Comment by soonick** [comment]
Hey KyraD,

The I have added your commit to my Master. You can look at my history and you'll see your name there.

Thanks for your help,
Adrian

**Pull request closed without merging**
